### ISSUE TITLE
cannot login as root

### ISSUE THREAD

**Issue by cameron** [saltstack/halite#108]
Having setup my external_auth block in /etc/salt/master with both root and a newly created user, only the newly created user is able to login to the halite web UI. (Yes, I reset the root password once to make sure this was not the issue.) If root is to be disallowed, a note in the docs would be great.

```
external_auth:
  pam:
    root:
      - .*
      - '@runner'
      - '@wheel'
    halite:
      - .*
      - '@runner'
      - '@wheel'
```

```
root@waterfront:~# salt --version
salt 0.17.4
root@waterfront:~/src/halite/halite# pip show halite

---
Name: halite
Version: 0.1.15
Location: /usr/local/lib/python2.7/dist-packages
Requires:
```
