### ISSUE TITLE
state.sls shows failed when it succeeds 

### ISSUE THREAD

**Issue by derekbelrose** [saltstack/halite#122]
Running a command such as state.sls shows failed when it succeeds.

Information:
vim-enhanced is not installed
/etc/vimrc is non existent

vim.sls

```
vim-enhanced:
 pkg.installed

/etc/vimrc:
 file.managed:
  - source: salt://vim/vimrc
  - mode: 644
  - user: root
  - group: root
```

New command:
`glob * state.sls vim`

Results are red, assuming it means bad.

Event pane:

```
 _stamp: 2014-02-10_11:51:21.642090 
cmd: _return 
fun: state.sls 
id: saltstack.local 
jid: 20140210115113144736 
out: highstate 
retcode: 2 
return: 
    file_|-/etc/vimrc_|-/etc/vimrc_|-managed: 
         __run_num__: 1 
        changes: 
             diff: New file 
             mode: 644 
        comment: File /etc/vimrc updated 
        name: /etc/vimrc 
        result: true 

     pkg_|-vim-enhanced_|-vim-enhanced_|-installed: 
          __run_num__: 0 
          changes: vim-enhanced: 
               new: 7.2.411-1.8.el6 
               old: 
               comment: The following packages were installed/updated: vim-enhanced. 
               name: vim-enhanced 
               result: true 
     stamp: 2014-02-10_11:51:21.642090 
     success: true
```
