### ISSUE TITLE
Issue authenticating with halite

### ISSUE THREAD

**Issue by alienzrcoming** [saltstack/halite#164]
Hi,

I've installed & configured halite referencing the documentation, but am unable to authenticate in the ui.  No error is displayed in the ui when I click 'Login' after entering my credentials, and no errors are logged in /var/log/salt/master.  note: I disabled TLS for now bc I was having a separate issue with that.  I've gotten this to work on earlier versions of salt (same halite configuration, tls disabled, etc..), but am revisiting halite with 2014.1.3.

Debian Wheezy / 7.4

salt --versions-report

```
           Salt: 2014.1.3
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

pip freeze

```
CherryPy==3.3.0
GitPython==0.3.2.RC1
Jinja2==2.6
M2Crypto==0.21.1
Mako==0.7.0
MarkupSafe==0.15
PyYAML==3.10
SOAPpy==0.12.0
argparse==1.2.1
async==0.6.1
chardet==2.0.1
distribute==0.6.24dev-r0
fpconst==0.7.2
gevent==1.0
gitdb==0.5.4
greenlet==0.4.2
halite==0.1.16
medusa==0.5.4
meld3==0.6.5
msgpack-python==0.1.10
pycrypto==2.6
python-apt==0.8.8.2
python-debian==0.1.21
python-debianbts==1.11
pyzmq==13.1.0
raven==3.5.2
reportbug==6.4.4
salt==2014.1.3
smmap==0.8.2
supervisor==3.0a8
wsgiref==0.1.2
```

cat /etc/salt/master.d/halite.conf 

```
halite:
  level: 'debug'
  server: 'cherrypy'
  host: '0.0.0.0'
  port: '80'
  cors: False
  tls: False

external_auth:
  pam:
    user1:
      - .*
      - '@runner'
      - '@wheel'
```

Only entries in /var/log/salt/master for halite is this:

```
2014-04-24 13:32:13,905 [salt.master                              ][INFO    ] Halite: Starting up ...
```

Any ideas on what I could be missing?

Thanks in advance
