### ISSUE TITLE
Documentation doesn't mention external_auth setting requirement

### ISSUE THREAD

**Issue by UtahDave** [saltstack/halite#26]
The doc doesn't mention a requirement to set the external_auth setting in /etc/salt/master

The following allowed my user to log in:

```
external_auth:
  pam:
    boucha:
      - .*
```

Is it possible to set more restrictive permissions for a specific user and still let that user in to the halite gui?
