### ISSUE TITLE
stormpath external_auth doesn't seem to work

### ISSUE THREAD

**Issue by UtahDave** [saltstack/halite#27]
I have a user named 'bobby' defined in my external_auth that uses stormpath for authentication.

relevant section of /etc/salt/master

```
external_auth:                                                                  
  stormpath:                                                                    
    bobby:                                                                      
      - .*                                                                      
  pam:                                                                          
    boucha:                                                                     
      - .*
```

From the CLI both users can authenticate and work:

```
[boucha@dasalt ~]$ salt -a stormpath '*' test.ping
username: bobby
password: 
dasalt:
    True
[boucha@dasalt ~]$ salt -a pam '*' test.ping
username: boucha
password: 
dasalt:
    True
```

I can log in to halite with user 'boucha', but not user 'bobby'.
When attempting to log in with user 'bobby' I get the following on the master:

```
[INFO    ] Clear payload received with command mk_token
[WARNING ] Authentication failure of type "eauth" occurred.
```

This is on a freshly cloned halite and the latest salt from git.

Does halite only allow for pam authentication?
